### ISSUE TITLE
AttributeError: python: undefined symbol: Error_GetLastErrorNum again

### ISSUE THREAD

**Issue by davidedelvento** [Toblerity/rtree#132]
Per your suggestion in issue #64 I am opening a new issue. The error is exactly the same as the one in #64 

Ubuntu v16.04
Python v3.5.2
libspatialindex v1.8.5 installed from source in `/usr/local/lib/`

rtree v0.9.3 downloaded from PyPI with pip3

I am trying libspatialindex v1.9.3 but that is failing for a plethora of other (unrelated) issues given the number of changes they made since v1.8.5 which break the rest of my system.

**Comment by hobu** [comment]
> given the number of changes they made since v1.8.5

What changes specifically? I manage both libspatialindex and Rtree. 

https://dev.azure.com/hobuinc/Rtree/_build/results?buildId=885 The ubuntu-16.04-pip and ubuntu-18.04-pip builds use Ubuntu's libspatialindex package. libspatialindex 1.8.5 is what is getting installed on both. The distutils `find_library` function is what is used to load it. If you've installed in a non-standard location, I think you're going to need to add `/usr/local/lib` to your `ld.so.conf` and run `ldconfig` or set `LD_LIBRARY_PATH`.

If previous versions of Rtree loaded from `/usr/local/lib` without intervention of `LD_LIBRARY_PATH` or `ldconfig` on your part, I would argue this convenience was a bug. We shouldn't be making assumptions about which paths to load from.

**Comment by davidedelvento** [comment]
> What changes specifically? I manage both libspatialindex and Rtree.

The first change was the download URL, so just changing the version in my ansible script failed with error 404. Fixed that, the problem was `/bin/sh: 1: ./configure: not found` because of the autoconf to cmake switch. We will see what life reserves for us next.

Regarding `LD_LIBRARY_PATH`, I am just doing the ansible equivalent of `sudo make install` and did not set any prefix in configure (now cmake). Since you manage both, it would be nice if the default installation prefix for libspatialindex would be one that rtree likes....

Otherwise, rather than messing with `ld.so.conf` or `LD_LIBRARY_PATH`, why would you not suggest me a prefix location to use?

**Comment by hobu** [comment]
> The first change was the download URL,

Yes, we moved libspatialindex's download location to GitHub rather than an obscure OSGeo URL that only I had access to upload to. This is so that someone else can pick up maintenance of the project.

> because of the autoconf to cmake switch.

Both were available previously, but it was extra effort to maintain them. CMake provides convenient windows configuration and builds, but autoconf only supports Linux and (sometimes) OSX. 

> Regarding LD_LIBRARY_PATH, I am just doing the ansible equivalent of sudo make install and did not set any prefix in configure (now cmake). Since you manage both, it would be nice if the default installation prefix for libspatialindex would be one that rtree likes....

The standard `CMAKE_INSTALL_PREFIX` on unix (and autoconf too for that matter) is `/usr/local` if you do not specify one. Change that to `-DCMAKE_INSTALL_PREFIX=/usr` when you invoke `cmake` and you should be good. It would be bad form to default that to `/usr` in libspatialindex's configuration because of the opportunity to clobber someone's system. We just follow convention there.

> Otherwise, rather than messing with `ld.so.conf` or `LD_LIBRARY_PATH`, why would you not suggest me a prefix location to use?

Given you are on 16.04, my suggestion would be to drop building your own libspatialindex entirely and just use the libspatialindex Ubuntu package that's in the default repositories. See https://github.com/Toblerity/rtree/blob/master/ci/azp/linux-1604-pip.yml for inspiration.

**Comment by davidedelvento** [comment]
@hobu Thanks for the suggestion. The apt install worked nicely with rtree and everything else seemed to work fine, so I switched to that. Hopefully things will stay stable this way.

Thanks a lot for your patience and assistance while working on this issue, I appreciate it.

Davide
