### ISSUE TITLE
Bulk insert in index loaded from file?

### ISSUE THREAD

**Issue by crypto-perry** [Toblerity/rtree#150]
Is it possible to load an index from file and then perform a bulk insertion?

I tried using both the filename and the stream parameters at the same time, but it appears the stream parameter simply creates a new index that overwrites the first one.
EG:
```
from rtree import index

p = index.Property()
p.dimension = 3
p.dat_extension = 'dat'
p.idx_extension = 'idx'

def bulk_insert_stream(n):
	for i in range(n):
		yield (i,(i, i, i, i, i, i), None)

spatial_idx = index.Index('spatial_idx', bulk_insert_stream(10000), properties=p, interleaved=False)
print(spatial_idx.count((0,1000000, 0, 1000000, 0, 1000000)))
#prints 10000
spatial_idx.close()
spatial_idx = index.Index('spatial_idx', properties=p, interleaved=False)
print(spatial_idx.count((0,1000000, 0, 1000000, 0, 1000000)))
#prints 10000
spatial_idx.close()
spatial_idx = index.Index('spatial_idx', bulk_insert_stream(100), properties=p, interleaved=False)
print(spatial_idx.count((0,1000000, 0, 1000000, 0, 1000000)))
# prints 100
spatial_idx.close()
```

So whenever I load the index with the stream parameter passed, there is nothing loaded from the file.

**Comment by sr-murthy** [comment]
A few points:

1. To get the index size count you don't need to manually pass the bounds - you can pass the `bounds` attribute to the `count` method, e.g.

    >>> print(spatial_idx.count(spatial_idx.bounds))
    10000

Another way to get the index size is via the new `get_size` method that was added in the last version (0.9.4 I think).

    >>> spatial_idx.get_size()
    10000

3. Unless I'm wrong, your statement to call the bulk insert streamer will override the previously created index object `spatial_idx` because it is part of a call to the `Index` constuctor to create an object of the same name but using a custom streamer. As far as I can see there is no method to do a bulk insert after creating an index.

4. According to the Rtree docs the stream argument to the `Index` constructor is to allow the creation of indexes in a faster way by enabling the data to be pre-sorted - as the stream must generate items it can be sorted prior to insert. It doesn't appear to be designed to support post-creation bulk inserts.

https://rtree.readthedocs.io/en/latest/performance.html#use-stream-loading

**Comment by hobu** [comment]
> It doesn't appear to be designed to support post-creation bulk inserts.

Correct. The point of bulk insertion is to pre-sort the data *before* insertion into the tree.

**Comment by dii14** [comment]
But why is it so much faster to insert even random data using stream insert at creation then? Is the library handling the sorting itself?

**Comment by hobu** [comment]
Yes, the library sorts the data in the stream before inserting. One-at-a-time insertion means each entry must fully traverse the tree as it is inserted. That requires more operations, more data wake-up, etc.
