### ISSUE TITLE
v0.9.6 prints "lost pointers" on exit

### ISSUE THREAD

**Issue by Helveg** [Toblerity/rtree#175]
Tried the new v0.9.6 on Windows and I get this message on exit:

```
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rtree.index import Index
>>> i = Index()
>>> exit()
Lost pointers: 0
Lost pointers: 0
Lost pointers: 0
Lost pointers: 0
```

**Comment by hobu** [comment]
Whoops, I think we built libspatialindex in debug mode @mikedh

**Comment by mikedh** [comment]
Ah that's interesting, I actually was copying in a new CMakeLists because the one in libspatialindex appeared to have a conditional which would always ignore the passed CMAKE_BUILD_TYPE argument on MSVC (lines in original CMakeLists)[https://github.com/libspatialindex/libspatialindex/blob/master/CMakeLists.txt#L102-L111]) so (I may totally be mistaken here) it was previously always building as RelWithDebInfo on Windows. 
 
 It looks like the built wheel on Windows is building as `Release`, here's the cmake call:
 https://github.com/Toblerity/rtree/blob/master/ci/install_libspatialindex.bat#L13
 And here's the build:
 https://github.com/Toblerity/rtree/runs/1595805402?check_suite_focus=true#step:6:1237
```
-- Looking for bcopy
-- Looking for bcopy - not found
-- Setting libspatialindex build type - Release
```
 
 We could change it back to `RelWithDebInfo`, although I'd probably hold off until a more severe (segfault/non-function) comes along and fix it then.

**Comment by mikedh** [comment]
Ah but yeah the MSCV is indeed building it as `debug|x64`:

```
Project "D:\a\rtree\rtree\libspatialindex-1.9.3\build\spatialindex.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
ValidateProjects:
```

**Comment by Helveg** [comment]
Can these new wheels be made available as a post-release perhaps?

**Comment by hobu** [comment]
> Can these new wheels be made available as a post-release perhaps?

I have issued a new release, and the new wheels should be updated within the hour.
