### ISSUE TITLE
Support for index intersection/union

### ISSUE THREAD

**Issue by adamjstewart** [Toblerity/rtree#209]
I would love to see support for computing the intersection (`&`) or union (`|`) between two rtree indices. We compute this manually in TorchGeo already ([intersection](https://github.com/microsoft/torchgeo/blob/v0.2.0/torchgeo/datasets/geo.py#L879,L884), [union](https://github.com/microsoft/torchgeo/blob/v0.2.0/torchgeo/datasets/geo.py#L990,L994)). A few questions:

1. Is there a way to do this natively in libspatialindex?
2. If not, do the above proposed implementations look reasonable?

If the answer to this is "no, yes", I can submit a PR. However, if it's possible to do this natively in libspatialindex, that's likely much more efficient.

**Comment by hobu** [comment]
The answer is "no, yes". Because libspatialindex has such an abstract API to its index types, it would be difficult to provide index algebra generically. What you're proposing for Rtree looks nice and convenient. Add a little bit of doc and test sugar around those and make a PR and I'll be happy to merge it.
