### ISSUE TITLE
pickle causes Immediate segfault

### ISSUE THREAD

**Issue by adq** [Toblerity/rtree#42]
Hi, if I run the following:
```
import rtree
import cPickle
x = rtree.index.Index()
cPickle.loads(cPickle.dumps(x))
```
I get a segfault when I quit python, (or at another random time later, depends how long it runs for). I've tried using plain 'pickle' as well, but get the same behaviour.

I'm using rtree 0.8.2 (installed via pip) against libspatialite 4.2.0-2 on arch linux x64, python 2.7.9

**Comment by kilink** [comment]
The issue here is that if an instance doesn't override __getstate__ and __setstate__, the pickler defaults to pickling the instance's __dict__ (the mapping of all attributes to values). If you look at what ends up in the serialized pickle, you'll quickly see that it includes the `handle` attribute, which is a pointer to an object allocated with libspatialindex.

This will cause problems when the Index is garbage collected, as the Index's __del__ method frees the underlying object. You're seeing the segfault because of this (essentially a double free).

The solution is to implement custom __getstate__ and __setstate__ methods...or to not try to pickle Index objects. Your use case is a little unclear, since rtree supports its own storage mechanism for serialiazing and deserializing the data structures.

Even if there are no plans to make Index objects pickle-able, it would be nice not to segfault here, and instead raise an exception.

**Comment by hobu** [comment]
I would happily merge a PR on this issue.

**Comment by kilink** [comment]
To implement pickling, or to simply prevent the segfault by throwing an exception instead in \_\_getstate\_\_ and \_\_setstate\_\_?

**Comment by hobu** [comment]
Ideally getting to the former, but the latter is a good start.
